Azure/autorest.powershell

- src/csharp/lowlevel-generator/support/enum.ts
- src/remodeler/main.ts
Comment out writing original yaml file to hard-coded directory.
Include the type name for 'ENUM AINT XMSENUM' failures.
> Fixes to unblock storage team

- src/common/code-model/schema.ts
- src/csharp/code-dom/statements/if.ts
- src/csharp/code-dom/statements/switch.ts
- src/csharp/lowlevel-generator/model/model-class.ts
- src/csharp/lowlevel-generator/operation/method.ts
- src/csharp/schema/array.ts
- src/csharp/schema/date-time.ts
- src/csharp/schema/primitive.ts
- src/csharp/schema/string.ts
- src/remodeler/remodeler.ts
Fixed reading header values.
Cleaned up URI creation and handling of query params.
Added some missing whitespace to various C# key words.
Fixed DateTime formatting preserving trailing zeroes.
Use InvariantCulter when parsing DateTime.
> First round of major codegen fixes

- extensions/powershell/resources/assets/build-module.ps1
- extensions/powershell/resources/runtime/GetProxyCmdlet.cs
- extensions/powershell/src/cmdlet-class.ts
- extensions/powershell/src/model-cmdlet.ts
Fixes: https://github.com/Azure/autorest/issues/3026
Fixes: https://github.com/Azure/autorest/issues/3033
Fixes: https://github.com/Azure/autorest/issues/3083
Created the cmdlet Get-ProxyCmdlet. This takes in the CommandInfo of the C# cmdlet variants and produces the proxy cmdlet scripts. For now, this outputs to `exports-new` so you can compare against the current `exports`. I also fixed a bug where `AsJob` was being marked as `DontShow` (which it shouldn't be marked as such).
> Created proxy cmdlet generator

- extensions/csharp-v2/src/exports.ts
- extensions/csharp-v2/src/schema/array.ts
- extensions/powershell/src/cmdlet-class.ts
- Fixes Issue: Any cmdlets that do not return a value should implement `PassThru` (https://github.com/Azure/autorest/issues/3082)
- Fixes Issue: OutputType for cmdlets should always be singular (non-collection) (https://github.com/Azure/autorest/issues/3085) 
- Also, fix for cmdlets that have multiple output types. Now, instead of stacking multiple OutputType attributes, it inserts an array of output types in one OutputType attribute.
> PassThru Implemetation, and OutputType fixes.

- extensions/csharp-v2/src/clientruntime.ts
- extensions/csharp-v2/src/project.ts
- extensions/powershell/resources/assets/build-module.ps1
- extensions/powershell/resources/runtime/Debugging.cs
- extensions/powershell/resources/runtime/NewProxyCmdlet.cs
- extensions/powershell/resources/runtime/NewTestStub.cs
- extensions/powershell/resources/runtime/PsAttributes.cs
- extensions/powershell/resources/runtime/PsExtensions.cs
- extensions/powershell/resources/runtime/PsProxyOutputs.cs
- extensions/powershell/resources/runtime/PsProxyTypes.cs
- extensions/powershell/src/cmdlet-class.ts
- extensions/powershell/src/model-cmdlet.ts
- extensions/powershell/src/powershell-declarations.ts
- extensions/powershell/src/project.ts
Added additional attributes to be used by the proxy generator. Updated implementation of proxy generator to have meta types that wrap the PowerShell types. They also have output types that tell them out to output into the script. Added new attributes to the generated cmdlets where appropriate. Fixed a bug with the help comment generation. Allowed output types to use all available distinct types.
> Proxy attributes

- extensions/powershell/resources/runtime/NewProxyCmdlet.cs
- extensions/powershell/resources/runtime/PsExtensions.cs
- extensions/powershell/resources/runtime/PsProxyOutputs.cs
- extensions/powershell/resources/runtime/PsProxyTypes.cs
- Collapsed parameter HelpMessage into a help comment (valid for script cmdlets)
- Removed `=$true` for boolean properties (not required)
- Moved cmdlet help comment to the top of the script
- Removed help forwarding from cmdlet help comment
- Normalized comma separated values
> Proxy generator, help cleanup

- extensions/powershell/resources/runtime/NewProxyCmdlet.cs
- extensions/powershell/resources/runtime/NewTestStub.cs
- extensions/powershell/resources/runtime/PsProxyTypes.cs
- extensions/powershell/src/generators/psm1.ts
- extensions/powershell/src/plugin-powershell.ts
- Added support for Profile attribute
- If profiles exist in any variants, will create 'profile' folders and any un-profiled variants are applied to all profiles
- If profiles don't exist on any variants, will do the same thing as the current proxy generator
- Module exports (psm1) will load 'latest' profile if there are directories in the `exports` folder
- 'latest' is the last directory in the folder
- If there are no directories, the files are flat in `exports` and will be loaded the same as it currently is loaded
- Updated tests to only generate stubs for non-generated variants/cmdlets
> Proxy: Profiles and tests

- extensions/powershell/resources/assets/.gitignore
- extensions/powershell/resources/assets/build-module.ps1
- extensions/powershell/resources/assets/generate-help.ps1
- extensions/powershell/resources/assets/run-module.ps1
- extensions/powershell/resources/assets/test-module.ps1
- extensions/powershell/resources/runtime/NewTestStub.cs
- extensions/powershell/src/generators/psm1.ts
This should be merged first: https://github.com/Azure/autorest.powershell/pull/78
PR in conjunction with: https://github.com/Azure/autorest/pull/3156
- Separates run isolation into a `run-module.ps1` script
- Allows someone to run the module isolated independent of building it
- Reused running called by `build-module.ps1`
- Removed dos-style coloring behavior
- Simplified calling so `run-module.ps1` simply runs itself isolated (instead of using `-Command` with a long string script)
- Running for `build-module.ps1` is now the `-Run` flag instead of `-Test`
- Fixed `pwsh` calling pattern to use `-File` instead of `-Command`
- **Custom script loading currently doesn't work** (will be fixed in follow-up PR)
- Removed `Push/Pop-Location` pattern to allow for easy configuration path loading …
> Clean up build scripts + add Pester testing

- extensions/powershell/project.ts
This was a bug where, the || operator was evaluating like this:
```
(await service.GetValue('prefix') || this.azure) ? 'Az' : ``
```
instead of like this:
```
await service.GetValue('prefix') || (this.azure ? 'Az' : ``)
```
> Ternary fix

- extensions/powershell/file-formats/psd-file.ts
- extensions/powershell/generators/csproj.ts
- extensions/powershell/generators/nuspec.ts
- extensions/powershell/generators/psd1.ts
- extensions/powershell/plugin-powershell.ts
- extensions/powershell/project.ts
- extensions/powershell/resources/assets/.gitignore
Fixes: https://github.com/Azure/autorest/issues/3175
Added fix for psd1 generating newlines on non-edit content. Properly represented the update/replace schema for root level files (psd1, csproj, nuspec). Properly excluded generated/build files for commit of module to a repo.
> Psd1 fix and misc dev experience

- extensions/csharp-v2/src/model/namespace.ts
- extensions/csharp-v2/src/operation/namespace.ts
- extensions/csharp-v2/src/support/namespace.ts
- extensions/powershell/README.md
- extensions/powershell/generators/nuspec.ts
- extensions/powershell/namespaces/model-extensions.ts
- extensions/powershell/namespaces/support.ts
- extensions/powershell/plugin-create-commands.ts
- extensions/powershell/project.ts
- extensions/powershell/test/test-service-name.ts
Fixes: https://github.com/Azure/autorest.powershell/issues/169
Fixes: https://github.com/Azure/autorest.powershell/issues/152
Fixes: https://github.com/Azure/autorest.powershell/issues/118
This moves the configuration defaults out of the project.ts and moves them into the readme for the PowerShell extension. 
Azure-specific defaults will be handled in a readme.azure.md in the Azure PowerShell repo.
> Configuration scaffolding

- extensions/powershell/model-cmdlet.ts
If you don't use --enable-multi-api, the object cmdlet names were generated incorrectly.
> Object cmdlet name fix

- extensions/csharp-v2/operation/method.ts
- extensions/csharp-v2/plugin-namer.ts
Addresses: https://github.com/Azure/autorest.powershell/issues/222
With this fix it does not fail in the same place. However, another issue with a file name being too long occurs:
Error: ENOENT: no such file or directory, open 'C:\azure-powershell\src\AppService\AppService\generated\cmdlets\SyncAzAppServiceWebAppFunctionTriggerSlot_ResourceGroupNameSlotSubscriptionIdEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtcEtc.cs'
> fix for unknown responseCodes

- extensions/powershell/generators/psm1.custom.ts
- extensions/powershell/generators/psm1.internal.ts
- extensions/powershell/generators/psm1.ts
- extensions/powershell/resources/runtime/ExportProxyCmdlet.cs
- extensions/powershell/resources/runtime/GetScriptCmdlet.cs
- extensions/powershell/resources/runtime/PsExtensions.cs
- extensions/powershell/resources/runtime/PsHelpers.cs
- extensions/powershell/resources/runtime/PsProxyOutputs.cs
- extensions/powershell/resources/runtime/PsProxyTypes.cs
- extensions/powershell/resources/runtime/SetPsd1Export.cs
Fixes: https://github.com/Azure/autorest.powershell/issues/120
Added alias support for both cmdlets and parameters. Properly exported the aliases from psd1 and psm1 files.
> Alias exporting support

- extensions/powershell/resources/runtime/PsProxyOutputs.cs
Fixed literal string to replace ‘, ’, and `<br>` with appropriate characters.
> Annoying quotes fix

- extensions/powershell/generators/nuspec.ts
- extensions/powershell/generators/psd1.ts
- extensions/powershell/project.ts
The metadata will populate the nuspec and psd1 file so they validate during packaging (building with -pack flag)
Previously only modules marked with the azure flag would pass the packaging process.
Metadata can be provided through the configuration file. The azure flag will override any provided metdata values.
If no metadata values are provided, sensible default will be used (empty string).
These changes makes it possible for organizations outside of Microsoft to use autorest.powershell generation in a CI pipeline and automatically publish the result to a nuget store (PSGallery for example).
The expected format is the following:
``` yaml
metadata: 
authors: string
requireLicenseAcceptance: true|false
description: string
copyright: string
tags: string
companyName: string
projectUrl: …
```
> Possible to configure additional metadata about the module. 

- extensions/powershell/cmdlet-class.ts
Fixes: https://github.com/Azure/autorest.powershell/issues/322
Instead of a file this gives info into the c# file when in debug mode.
> Debug update -adding cmdlet details to c# comment header 

- extensions/powershell/resources/assets/generate-help.ps1
Addressed https://github.com/Azure/autorest.powershell/issues/335 where the generate-help was incorrectly obtaining the exports directory object. This caused an error when attempting to obtain the cmdlets because the path string did not have a FullName property.
> Addressed Issue:335

- extensions/powershell/resources/assets/build-module.ps1
- extensions/powershell/resources/built-time-cmdlets.csproj
- extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportHelpMarkdown.cs
- extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
- extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportPsd1.cs
- extensions/powershell/resources/runtime/BuildTime/Models/PsMarkdownTypes.cs
- extensions/powershell/resources/runtime/BuildTime/Models/PsProxyOutputs.cs
- extensions/powershell/resources/runtime/BuildTime/Models/PsProxyTypes.cs
Fixes: https://github.com/Azure/autorest.powershell/issues/321
This uses the InfoAttribute and outputs complex parameter information into the Notes section of both the exports and the markdown documents.
Based on these changes, I've created another issue to revise this implementation. I consider this PR the 'first iteration' of this feature.
https://github.com/Azure/autorest.powershell/issues/388
> Complex type documentation

- extensions/powershell/resources/runtime/BuildTime/Models/PsProxyTypes.cs
Fixes: https://github.com/Azure/autorest.powershell/issues/405
> Allows the implemented interfaces of the types to get recognized by the complex type documentation generator.

- extensions/powershell/resources/runtime/BuildTime/Models/PsProxyTypes.cs
Allow binary cmdlets with multiple versions - use '!' as a separator, with the proxy cmdlet name in the first part.
Note that '!' looks like the best choice to be the separator, as most other characters (including '@') are on a reserved list, and will produce a warning on import.  The other possibility  in the typewriter characters was '%'
> Allow multi-version binary cmdlets

- extensions/csharp-v2/operation/method.ts
- extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportCmdletSurface.cs
This updates the cmdlet surface to include output types from the cmdlets. Also, minor fix for when Delta is missing from the RetryAfter header.
> Surface output types + minor fix

- extensions/powershell/README.md
- extensions/powershell/project.ts
- extensions/powershell/resources/runtime/BuildTime/Models/PsHelpMarkdownOutputs.cs
- extensions/powershell/resources/runtime/BuildTime/Models/PsProxyTypes.cs
Fixes: https://github.com/Azure/autorest.powershell/issues/378
Added helpLinkPrefix to allow setting the base URL for help documentation links.
> Help link prefix

- extensions/csharp-v2/operation/method.ts
Despite the latest regex/query param change i'm still seeing issues with query parameters and stray `&`.  (referencing #442 and #445 )
Specifically, seeing GETs like this:
`GET /RESOURCE?&guid=039467b3-d779-493c-91ec-7137395a9582`  
Note the `?&`.  
Upon inspection I expected your regex to catch this case, but wasn't able to adapt what you have.  I'm simply adding a `.Replace("&?", "?")` in the interim, and that's doing the trick for me.
I'm sure there's a cleaner fix to this, but I wanted to surface the issue to you nonetheless.
@kenal-microsoft  @amareshbAtMicrosoft
> my fix for ?&

- extensions/powershell/generators/csproj.ts
- extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportHelpMarkdown.cs
- extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportModelSurface.cs
- extensions/powershell/resources/runtime/BuildTime/Models/PsHelpMarkdownOutputs.cs
Properly excluded files from the resources folder in the csproj generator. Fixed displaying descriptions in markdown when they contain <> characters. Cleaned up the ExportModelSurface. Allowed ExportModelSurface to show both enum values (if property is an enum) and associative array type (if either type or properties are IAssociativeArray).
> Multiple small fixes

- powershell/enums/namespace.ts
Creates a typeconverter class for enum structs:
``` csharp
namespace Microsoft.Azure.PowerShell.Cmdlets.Dns.Support
{
/// <summary>TypeConverter implementation for HttpStatusCode.</summary>
public partial class HttpStatusCodeTypeConverter :
System.Management.Automation.PSTypeConverter
{
/// <summary>
/// Determines if the converter can convert the <see cref="sourceValue"/> parameter to the <see cref="destinationType" />
/// parameter.
/// </summary>
/// <param name="sourceValue">the <see cref="System.Object"/> to convert from</param>
/// <param name="destinationType">the <see cref="System.Type" /> to convert to</param>
/// <returns>
/// <c>true</c> if the converter can convert the <see cref="sourceValue"/> parameter to the <see cref="destinationType" />
/// parameter, otherwise …
```
> added typeconverter for enum structs

- powershell/resources/psruntime/HttpPipelineMocking.ps1
The mock step should be put in the front, otherwise we will not be able to run the playback mode without login (connect-azaccount)
> Fix a mock issue for test

- powershell/generators/nuspec.ts
On OS X `pack-module.ps1` is including the content of _custom/docs/exports/internal_ in the top level of the generated .nupkg rather than maintaining the directory structure.
Based on https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-assembly-files a target attribute is required to ensure the correct structure is achieved
> Adding target attribute to nuspec file elements

- powershell/cmdlets/class.ts
- powershell/module/module-class.ts
Emit Signal method and delegate to provide hook into events for Non-Azure scenarios.
If no event is attached to `EventListener`, making it null, invocation will be skipped.
> Emit Signal method and delegate to provide hook into events for Non-Azure scenarios.

- powershell/autorest-configuration.md
- powershell/cmdlets/class.ts
- powershell/cmdlets/namespace.ts
- powershell/llcsharp/model/model-class.ts
- powershell/llcsharp/operation/method.ts
- powershell/llcsharp/operation/parameter.ts
- powershell/llcsharp/schema/schema-resolver.ts
- powershell/main.ts
- powershell/module/module-class.ts
- powershell/plugins/add-azure-completers-v2.ts
- powershell/plugins/create-commands-v2.ts
- powershell/plugins/cs-namer-v2.ts
- powershell/plugins/plugin-create-inline-properties.ts
- powershell/plugins/plugin-tweak-model-azure-v2.ts
- powershell/plugins/plugin-tweak-model.ts
- powershell/plugins/ps-namer-v2.ts
1. support get/post/put/delete/patch
2. support request body
3. support api-version in query parameter
> support request body

- tests-upgrade/AutoRestUpgradeTest.ps1
Change the AutoRestUpgrade.ps1 to determine whether it is a folder more accurately in different Powershell version.
> Change the AutoRestUpgrade.ps1 for different Powershell version

- powershell/autorest-configuration.md
- powershell/cmdlets/class.ts
- powershell/enums/namespace.ts
- powershell/llcsharp/enums/enum.ts
- powershell/llcsharp/model/namespace.ts
- powershell/llcsharp/operation/method.ts
- powershell/llcsharp/schema/enum.ts
- powershell/llcsharp/schema/schema-resolver.ts
- powershell/llcsharp/schema/string.ts
- powershell/main.ts
- powershell/plugins/create-commands-v2.ts
- powershell/plugins/cs-namer-v2.ts
- powershell/plugins/modifiers-v2.ts
- powershell/plugins/plugin-tweak-model.ts
- powershell/utils/schema.ts
- tests-upgrade/Configuration.json
1. add support for enum (no test cover yet)
2. add more test 
- "component-param",
- "component-multiparam",
- "component-param-localremote",
- "component-param-inbody"
> Support enum

- powershell/internal/project.ts
- powershell/llcsharp/schema/date-time.ts
- powershell/llcsharp/schema/date.ts
- powershell/llcsharp/schema/schema-resolver.ts
- powershell/models/model-extensions.ts
- powershell/plugins/create-commands-v2.ts
- powershell/plugins/cs-namer-v2.ts
- powershell/plugins/plugin-tweak-m4-model.ts
- powershell/plugins/plugin-tweak-model.ts
- tests-upgrade/Configuration.json
Add test datamodels-datatypes-file
We cannot enable following cases. They will make ci failed. But they are not blocking issues.
**1. For cases: datamodels-datatypes-boolean, datamodels-datatypes-date, datamodels-datatypes-byte**
a. comment in /* diff:
```
datamodels-datatype-boolean - \generated\api\DatabricksClient.cs
datamodels-datatypes-byte - \generated\api\DatabricksClient.cs
datemodels-datatypes-date - \generated\api\DatabricksClient.cs
```
b. Body parameter description is lost in m3:
`\generated\cmdlets\SetAzDatabricksByteNonAscii_Put.cs`
**2. For case: component-param-resourceasarraay**
a. For schema definied in response, m3 and m4 will use different name pattern. It's not visiable for user and won't block command execution
```
\generated\api\DatabricksClient.cs …
```
> fix some issues

- powershell/autorest-configuration.md
- powershell/llcsharp/operation/method.ts
- powershell/plugins/create-commands-v2.ts
To support multipart, m4 add new content parameter into request. We should skip this parameters
> skip content type request parameter

- powershell/internal/project.ts
- powershell/llcsharp/schema/schema-resolver.ts
Fix some issue after using new m4.
CI for datamodels-datatypes-boolean, datamodels-datatypes-date and datamodels-datatypes-datetime will still failed due to /* issue
> Fix choice issue

- powershell/cmdlets/class.ts
M4 does not allow constant response. If response is constant it will change to corresponding schema.
> Fix enum boolean response which has only one value

- powershell/llcsharp/model/model-class-json.ts
fix #625
Root cause: when generating code to deserialize dictionary values, the old logic is wrong so that when value is object, it will default to not do the serialization.
> fix deserialize dictionary value bug

- powershell/resources/assets/custom/readme.md
Correct the namespace of helper attributes mentioned in `custom/readme.md`.
Fix #672
Sample output:
```markdown
For processing the cmdlets, we've created some additional attributes:
- `Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.DescriptionAttribute`
- Used in C# cmdlets to provide a high-level description of the cmdlet. This is propegated to reference documentation via [help comments](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help) in the exported scripts.
- `Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.DoNotExportAttribute`
- Used in C# and script cmdlets to suppress creating an exported cmdlet at build-time. These cmdlets will *not be exposed* by `Az.AppConfiguration`.
- …
```
> fix the namespace of attibutes in custom/readme

- powershell/resources/assets/build-module.ps1
- powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
Currently the code path below, throws `ArgumentNullException` when `Export-ProxyCmdlet` is invoked in the `-NoDocs` code path.
https://github.com/Azure/autorest.powershell/blob/f9b8e887b9787c1d21727a6db4f1095b2601b506/powershell/resources/assets/build-module.ps1#L123-L134
Exception is thrown here at `Path.Combine`, since `ExamplesFolder` will be null.
https://github.com/Azure/autorest.powershell/blob/6390998136582908155e819cc9393aa95bd2c33a/powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs#L76
***Solution***
Allow `ExamplesFolder` to be passed along for all param sets, since examples are already always generated. (Example Stubs).
https://github.com/Azure/autorest.powershell/blob/6390998136582908155e819cc9393aa95bd2c33a/powershell/resources/psruntime/BuildTime/Cmdlets/Ex …
> Fix ArgumentNullException when Generating without docs `-NoDocs` switch

- powershell/llcsharp/operation/method.ts
- powershell/resources/runtime/csharp/client/UndeclaredResponseException.cs
fix https://github.com/Azure/autorest.powershell/issues/580
fix https://github.com/Azure/autorest.powershell/issues/613
During long running operation polling, if state is failed, throw an exception with message from `error` or `properties.statusMessage`.
> throw undelaredResponseException when LRO

- powershell/plugins/plugin-create-inline-properties.ts
Should not generate parameter for inherited readonly property
> Fixed https://github.com/Azure/autorest.powershell/issues/725

- powershell/resources/assets/test-module.ps1
- powershell/resources/psruntime/BuildTime/Cmdlets/ExportTestStub.cs
```powershell
Describe 'New-AzDatabricksWorkspace' -Tag 'LiveOnly'{
}
```
```powershell
./test-module.ps1 -TestName Get-AzDatabricksWorkspace,new-AzDatabricksWorkspace
```
```powershell
./test-module.ps1 -TestName Get-AzDatabricksWorkspace,new-AzDatabricksWorkspace -Record -UsePreviousConfigForRecord
```
**Previous**
```powershell
$null = $env.Add("rstr5", $rstr5)
```
**Now**
```powershell
$rstr5 = $env.AddWithCache("rstr5", $rstr5, $UsePreviousConfigForRecord)
```
Or
Use following if some values are generated in service side.
```powershell
$rstr5 = $env.AddWithCache("rstr5", $rstr5, $false)
```
Add following **if** clause in the header of each test script which ends with .Tests.ps1. And you should replace 'Get-AzDatabricksVNetPeering' with the name in your test **Describe**. …
> Improvement for test, #789 and #788

- powershell/generators/psm1.ts
- powershell/internal/project.ts
- powershell/llcsharp/model/namespace.ts
- powershell/models/model-extensions.ts
- powershell/module/module-class.ts
For dataplane, following two configurations are required in readme.md.
```
endpoint-key-name: "AppConfigurationEndpointResourceId"
endpoint-suffix-key-name: "AppConfigurationEndpointSuffix"
```
And besides, users could implement `partial void CustomInit()` in their custom code to add a `tokenaudienceconverter` and assign it to `_tokenAudienceConverter  `
> Add initial support for data plane

- powershell/cmdlets/class.ts
- powershell/cmdlets/namespace.ts
- powershell/plugins/modifiers-v2.ts
- powershell/resources/psruntime/AsyncCommandRuntime.cs
- powershell/resources/psruntime/BuildTime/MarkdownRenderer.cs
- powershell/resources/psruntime/BuildTime/Models/PsMarkdownTypes.cs
- powershell/resources/psruntime/BuildTime/Models/PsProxyTypes.cs
- powershell/resources/runtime/csharp/client/Extensions.cs
Related issue is https://github.com/Azure/autorest.powershell/issues/253.
To support client side pagination, normally there are two steps need to be done.
1. If the skip or first/top have been supported by service, these parameters should be removed from swagger through autorest transform directive
2.  Client side pagination is enabled through directive on cmdlet/variant level. And following is an example.
```
- where:
verb: Get
variant: ^List(.*)
set:
clientside-pagination: true  
```
> Add support for client side pagination

- powershell/plugins/cs-namer-v2.ts
- powershell/plugins/plugin-tweak-m4-model.ts
If an object both contains properties and additionalproperties, there will be a redundant model class generated, And this change is to fix it.
> Prevent redundant model generation

- powershell/generators/psm1.ts
- powershell/internal/project.ts
- powershell/resources/assets/build-module.ps1
- powershell/resources/assets/check-dependencies.ps1
- powershell/resources/assets/create-model-cmdlets.ps1
- powershell/resources/assets/export-surface.ps1
- powershell/resources/assets/generate-help.ps1
- powershell/resources/assets/pack-module.ps1
- powershell/resources/assets/run-module.ps1
- powershell/resources/assets/test-module.ps1
- powershell/resources/assets/test/loadEnv.ps1
- powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
- powershell/utils/powershell-comment.ts
Add `--pwsh-license-header` to set license header for generated powershell code.
If `--pwsh-license-header` is not set, `--license-header` is applied.
And magic words for this setting include:
- microsoft_mit_no_version
- microsoft_apache_no_version
- microsoft_apache_no_codegen
- microsoft_mit_small_no_codegen
> Add --pwsh-license-header to set license for generated powershell code

- powershell/internal/project.ts
- powershell/resources/psruntime/BuildTime/Cmdlets/ExportFormatPs1xml.cs
1. Remove hardcode excluded property Id for Azure services
2. Add a configuration for users to exclude properties from table view
> Following is an example
``` yaml $(default-exclude-tableview-properties)
exclude-tableview-properties:
- Id
- Type
```
> Add a configuration for users to exclude properties from table view

- powershell/resources/runtime/csharp/json/Customizations/IJsonSerializable.cs
This PR closes https://github.com/Azure/autorest.powershell/issues/867 by ensuring we fully serialize `DictionaryEntry` types into JSON. [DictionaryEntry](https://docs.microsoft.com/en-us/dotnet/api/system.collections.dictionaryentry?view=net-5.0) is a struct and should be serialized when handling value types.
> Serialize `DictionaryEntry` types as value types

- powershell/resources/psruntime/BuildTime/Models/PsHelpMarkdownOutputs.cs
Fixed https://github.com/Azure/autorest.powershell/issues/871, should use synopsis instead of description in module page
> Use synopsis in module page

- powershell/llcsharp/operation/method.ts
- powershell/resources/psruntime/BuildTime/Models/PsMarkdownTypes.cs
This change is to support wildcard response status supported in OAS 3 as blelow.
> Any HTTP status code can be used as the property name, but only one property per code, to describe the expected response for that HTTP status code. A Reference Object can link to a response that is defined in the OpenAPI Object's components/responses section. This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML. To define a range of response codes, this field MAY contain the uppercase wildcard character X. For example, 2XX represents all response codes between [200-299]. Only the following range definitions are allowed: 1XX, 2XX, 3XX, 4XX, and 5XX. If a response is defined using an explicit code, the explicit code definition takes precedence over the …
> Add support for wildcard response code supported in oas 3

- powershell/package.json
- powershell/resources/runtime/csharp/json/Customizations/IJsonSerializable.cs
This PR applies changes made in main branch to MsGraph branch to ensure we fully serialize hashtables.
Unblocks https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/954
> Hashtable Serialization

- powershell/plugins/ps-namer-v2.ts
The swagger that triggers this issue is as https://github.com/Azure/azure-rest-api-specs/blob/main/specification/guestconfiguration/resource-manager/Microsoft.GuestConfiguration/stable/2020-06-25/examples/listAllGuestConfigurationAssignmentReports.json#L51.
> Fixed an issue caused by details: null is set in examples of swagger

- powershell/llcsharp/schema/primitive.ts
- powershell/plugins/ps-namer-v2.ts
Some rest API will return a primitive type like integer, bool instead of a json object. And this change is for that. And  https://github.com/Azure/autorest.powershell/issues/892 is one of the cases.
> Add support for response of primitive type

- powershell/llcsharp/schema/byte-array.ts
The fix is for sting like following in swagger.
```
"base64url": {
"type": "string",
"format": "base64url"
}
```
> Add support for base64url

- powershell/module/module-class.ts
Fix for https://github.com/Azure/autorest.powershell/issues/902
> Need to recreate the httpclienthandler when proxy is disabled/enabled

- powershell/llcsharp/schema/array.ts
Enum is implemented as a struct in the generated code, so can not use ?. operator.
> Fix an enum array related issue in query parameter

- powershell/resources/assets/internal/README.md
The old link is invalid. Let's point it to the new link - https://github.com/Azure/autorest.powershell/blob/main/docs/directives.md#cmdlet-hiding-exportation-suppression
> Fixed the cmdlet hiding link

- powershell/resources/assets/create-model-cmdlets.ps1
We should use subject-prefix instead of module name in model cmdlet
> Use subject-prefix in model cmdlet

- powershell/cmdlets/class.ts
- powershell/llcsharp/model/model-class.ts
- powershell/models/model-extensions.ts
- The space in tag < see> should be removed.
```
/// A < see cref = "global::System.Threading.Tasks.Task" /> that will be complete when validation is completed.
->
/// A <see cref = "global::System.Threading.Tasks.Task" /> that will be complete when validation is completed.
```
See https://github.com/Azure/autorest.powershell/issues/842
- <paramref name="destinationType" /> should be removed from
```
/// <summary>
/// Determines if the converter can convert the <see cref="sourceValue"/> parameter to the <see cref="destinationType" />
/// parameter.
/// </summary>
public static bool CanConvertFrom(dynamic sourceValue)
{}
```
- Full namespace
```
<see cref="IEventListener" />
-> 
<see cref="Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.Runtime.IEventListener" />
```
- Replace …
> Correct bad format in XML comments

- .scripts/publish.yaml
The change is needed by the azure pipeline so that we could use the version from the package.json directly.
> Add support to specify the version manually

- powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
The root cause is when users run `foreach-object -Parallel`, $Host.Runspace.Version will be null.
> Fix an issue when users run 'foreach-object -Parallel'

- powershell/resources/psruntime/BuildTime/PsHelpers.cs
- powershell/resources/runtime/csharp/pipeline/PipelineMocking.cs
In .net framework 4 which is used by Windows PowerShell, uri.tostring function will un-escaped %2B to plus(+).
> Fixed two minor issues - single quote related and uri.tostring related

- powershell/cmdlets/class.ts
- powershell/plugins/modifiers-v2.ts
- powershell/utils/command-operation.ts
The directive to add a parameter should be as below.
```
- where:
subject: subject-name
variant: variant-name
add:
parameters:
- name: name
type: string
required: true
completer:
name: xxx
description: xxx
script: xxx
default:
name: xxx
description: xxx
script: xxx
description: "This is a parameter"
```
> Initial support to add cmdlet parameters through directive

- powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
This PR is supposed to fix issues https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/44 and https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1135. 
The fix is as a result of guidance from docs (https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/disallowed-html-tag?branch=main) information on unrestricted HTML containing scripting that can be used to hack docs site.
The particular scripting found is the angle brackets used as placeholders.
> Escape angle brackets for placeholders

- powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
This PR is a replication of the merge that was done to main branch from this [PR](https://github.com/Azure/autorest.powershell/pull/958). The fix addresses security issues raised [here](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/disallowed-html-tag?branch=main)
> Escape angle brackets using backticks

- powershell/cmdlets/class.ts
- powershell/plugins/modifiers-v2.ts
- powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
- powershell/resources/psruntime/BuildTime/Models/PsProxyTypes.cs
- powershell/resources/runtime/csharp/client/InfoAttribute.cs
The syntax should be as below.
```
- where:
parameter-name: SubscriptionId
set:
default:
script: '(Get-AzContext).Subscription.Id'
set-condition: "$PSBoundParameters.ContainsKey('some-other-parameter')"
```
> Add condition check for default value directive

- powershell/resources/psruntime/BuildTime/Cmdlets/ExportPsd1.cs
This PR closes #976 by ensuring prerelease module versions in psd1 are surrounded in quotes as stated in [PowerShell module prerelease support](https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/module-prerelease-support?view=powershell-7.2#identifying-a-module-version-as-a-prerelease).
> Enclose prerelease module versions in psd1 with quotes

- powershell/resources/psruntime/BuildTime/Models/PsMarkdownTypes.cs
... so that developer would know to remove the whole "```output" block when the example has no output.
> Update template of example

- powershell/autorest-configuration.md
- powershell/cmdlets/class.ts
- powershell/internal/powershell-declarations.ts
- powershell/llcsharp/schema/schema-resolver.ts
- powershell/llcsharp/schema/uri.ts
- powershell/plugins/create-commands-v2.ts
- powershell/plugins/plugin-create-inline-properties.ts
- powershell/plugins/plugin-tweak-model.ts
- powershell/resources/psruntime/Attributes/ExternalDocsAttribute.cs
- powershell/resources/psruntime/BuildTime/Models/PsMarkdownTypes.cs
- powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
- powershell/resources/psruntime/BuildTime/Models/PsProxyTypes.cs
- powershell/utils/components.ts
Support ExternalDocs for autorest.powershell
- if externalDocs is added to operation, its content will be added to three parts:
- the attribute of c# cmdlet
- the result of Get-Help {cmdlet-name} 
- the  related links section of docs/MDs
See generated details: https://github.com/Azure/azure-powershell/blob/demo/Search/src/Search/docs/New-AzSearchService.md#related-links
- Support adding externalDocs by customization
see https://github.com/Azure/azure-powershell/blob/demo/Search/src/Search/docs/Get-AzSearchAdminKey.md#related-links
- if externalDocs is added to parameter, its content will be added to parameter description:
- if externalDocs is added to property, its content will be add to the xml comment of property:
See generated details from demo projects: …
> Support ExternalDocs for autorest.powershell

- powershell/llcsharp/schema/enum.ts
This PR closes #973 by adding `deserializeFromResponse` method to `EnumImplementation` class in `schema/enum.ts` for deserializing enum responses. The old implementation relied on `deserializeFromResponse` method from the extended `String` class.
> Deserialize Enum Responses

- powershell/plugins/sdk-tweak-model.ts
- powershell/resources/templates/method.ejs
- powershell/resources/templates/methodBodyRestCall.ejs
- powershell/resources/templates/methodGroupInterface.ejs
- powershell/sdk/utility.ts
Below is an example of swagger.
```
{
"name": "parameters",
"in": "body",
"x-ms-client-flatten": true,
"required": true,
"schema": {
"$ref": "#/definitions/operation"
},
"description": "Parameters supplied to the create or update a workspace."
}
```
> sdk - Add support for x-ms-client-flatten in request body

- powershell/plugins/sdk-tweak-model.ts
- powershell/resources/templates/longRunningOperationMethod.ejs
- powershell/resources/templates/method.ejs
[Bug fix] Removed unexpected ? in constructor parameters declaration
```dotnetcli
public AgentPoolAvailableVersions(string id = default(string), string name = default(string), string type = default(string), System.Collections.Generic.IList<AgentPoolAvailableVersionsPropertiesAgentPoolVersionsItem> agentPoolVersions = default(System.Collections.Generic.IList<AgentPoolAvailableVersionsPropertiesAgentPoolVersionsItem>))
{
this.Id = id;
this.Name = name;
this.Type = type;
this.AgentPoolVersions = agentPoolVersions;
CustomInit();
}
```
```dotnetcli
public AgentPoolAvailableVersions(string id = default(string), string name = default(string), string type = default(string), System.Collections.Generic.IList<AgentPoolAvailableVersionsPropertiesAgentPoolVersionsItem>? agentPoolVersions = …
```
> [Provider-aks] Fixed issue in model constructor parameters declaration

- docs/directives.md
Add a link to breaking change directive and preview directive in `directives.md`.
> Add a link to breaking change directive in directives.md

- powershell/resources/templates/model.ejs
[Here ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2022-08-15-preview/dataTransferService.json#L297)is an example swagger.
For the case above, we will generate a model class without properties, in which there are two same constructors without parameters generated. And we need to remove one.
> sdk - remove redundant constructor for model without properties

- powershell/cmdlets/class.ts
- powershell/resources/assets/generate-portal-ux.ps1
Currently the unexpanded object from http body will miss the `Category` attribute.
> Add category for body object

- powershell/llcsharp/csharp-declarations.ts
- powershell/llcsharp/model/model-class.ts
- powershell/resources/assets/create-model-cmdlets.ps1
- powershell/resources/psruntime/BuildTime/PsAttributes.cs
Discriminator is fixed when we create an instance of a child class, so the parameter is useless in auxiliary cmdlet.
> v4 - remove discriminator parameter in auxiliary cmdlet

- powershell/internal/project.ts
- powershell/resources/assets/build-module.ps1
- powershell/resources/assets/create-model-cmdlets.ps1
Directive for model-cmdlet changed from
```
- model-cmdlet
- xxx
```
to
```
- model-cmdlet
- model-name: xxx
model-cmdlet: yyy
```
> v4 - support setting cmdlet name for model cmdlet

- powershell/llcsharp/project.ts
- powershell/plugins/llcsharp-v2.ts
- powershell/resources/runtime/csharp/pipeline/ISendAsync.cs
There are two kinds of retries.
1. Retry on error
Default retry time is 3, but can be overridden by env variable PS_HTTP_MAX_RETRIES and AZURE_PS_HTTP_MAX_RETRIES (most high priority)
3. retry on 429 with retry-after
Default retry time will be max(int), but can be overridden by env variable PS_HTTP_MAX_RETRIES_FOR_429 and AZURE_PS_HTTP_MAX_RETRIES_FOR_429 (most high priority)
> Add retry support in v4

- powershell/internal/project.ts
- powershell/llcsharp/project.ts
We need to set up default directives and configuration if module is under Azure PowerShell. For instance:
resourcegroup-append should be true
identity-correction-for-post: true
export-properties-for-dict: true
nested-object-to-string：true
> Change default values for azure  case

- powershell/plugins/modifiers-v2.ts
setting keep-PEC-and-PLR: true in directive will keep these cmdlets
> Remove private endpoint endpoint and private link resource related commands by default

- powershell/cmdlets/class.ts
- powershell/plugins/modifiers-v2.ts
- powershell/utils/command-operation.ts
This directive is especially useful for some post APIs like listkey or checksomething, which actually does not require shouldprocess for generated cmdlets
```
- where:
verb: Get
set:
suppress-should-process: true
```
> v4 - add directive to suppress shouldprocess, fixed #704

- powershell/cmdlets/class.ts
Fixed the issue [#952]. Following things were updated.
* Return the object instead of the property even if it has only one property
* The OutputType for the cmdlet is the interface of the object instead of the primitive type of the property
> Return the object even it has one property. Fixed [#952]

- powershell/plugins/ps-namer-v2.ts
Do not use the singularName if there is a name conflict.
> v4 - Fixed an issue wrt the name conflict

- powershell/resources/assets/build-module.ps1
- powershell/resources/assets/generate-help.ps1
- powershell/resources/psruntime/BuildTime/Cmdlets/ExportHelpMarkdown.cs
- powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
- powershell/resources/psruntime/BuildTime/MarkdownRenderer.cs
> Remove complex interface information from help markdown

- powershell/cmdlets/class.ts
Sometimes service will return an empty string instead of null, which it should be. And this enhancement is added for the case like this.
Related issue is https://github.com/Azure/autorest.powershell/issues/982.
> v4 - stop getting next page if nextlink is an empty string

- powershell/resources/psruntime/BuildTime/PsHelpers.cs
AutoRest.PowerShell code has the logic to keep GUID reused when building a module. The issue was caused by the psd1 indent. It searched `  GUID` in the psd1 to see if a GUID existed. When a psd1 is updated by `Update-ModuleManifest`, the 2 spaces before the `GUID` will be removed. Thus it considered there was no GUID generated.
> Keep consistent GUID after updating psd1. Fixed issue [#981]

- powershell/plugins/sdk-tweak-model.ts
- powershell/resources/templates/model.ejs
- powershell/sdk/utility.ts
1. If x-ms-azure-resource is set, will inherent from Microsoft.Rest.Azure.IResource and other parents will be ignored
2. For member with const properties, need to new it in the constructor without parameters.
> Fixed two issues related to x-ms-azure-resource and constructor without parameters

- powershell/cmdlets/class.ts
fixing #1198 
API ```List=>POST:"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Elastic/monitors/{monitorName}/listAllTrafficFilters"```
was treated as list operation, thus the list viaidentity cmdlet append action 'listAllTrafficFilters' for identity '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Elastic/monitors/{monitorName}'
```
if (MonitorInputObject?.Id != null)
{
this.MonitorInputObject.Id += "/listAllTrafficFilters";
await this.Client.AllTrafficFiltersListViaIdentity(MonitorInputObject.Id, onOk, onDefault, this, Pipeline);
}
```
Add check for list operations, if it's post API, append nothing to the identity.
> do not append action for post viaidentity

- powershell/resources/psruntime/BuildTime/Cmdlets/ExportTestStub.cs
Currently part of the test cases invokes Start-Sleep to wait for a specific period of time until the required resources are ready. However, in the scenario test, it is absolutely not necessary during playback mode. It has increased the total amount of test execution time in the CI. In this PR, we introduce a new function called `Start-TestSleep` to avoid the unnecessary wait time.
> Add Start-TestSleep to avoid waiting during playback mode

- powershell/plugins/plugin-create-inline-properties.ts
Fixed https://github.com/Azure/autorest.powershell/issues/1290
> Expanded parameters should be optional if the entire body parameter is optional

- powershell/cmdlets/class.ts
- powershell/generators/psm1.ts
- powershell/module/module-class.ts
This pull request introduces several changes to the PowerShell cmdlets and module classes in the `powershell/cmdlets/class.ts`, `powershell/generators/psm1.ts`, and `powershell/module/module-class.ts` files. The changes mainly focus on implementing telemetry and output sanitization features. The most significant changes include the addition of a new `NewImplementWriteObject` method, the introduction of new delegates for sanitizing output and getting telemetry information, and the inclusion of these delegates in the `CmdletClass` and `NewModuleClass`.
Telemetry and Output Sanitization:
* [`powershell/cmdlets/class.ts`]: Added a new method `NewImplementWriteObject` to sanitize output objects and write them to the pipeline. This method includes two overloads for handling single objects and …
> Implement sanitizer handler for autorest modules

- powershell/cmdlets/class.ts
This pull request includes changes to the `CmdletClass` in the `powershell/cmdlets/class.ts` file. The changes primarily focus on improving the handling of telemetry information and warnings related to the display of secrets.
Key changes:
* [`powershell/cmdlets/class.ts`]: Added a new line to retrieve the `ShowSecretsWarning` value from `telemetryInfo`. This value is then used to control whether a warning about displaying secrets is shown. The conditional statement for displaying the warning has been updated to check the `ShowSecretsWarning` value instead of checking if `sanitizedProperties` is not null or empty. If `ShowSecretsWarning` is "true", it checks if `sanitizedProperties` is null or empty. If it is, a general warning about showing secrets is displayed. Otherwise, a detailed …
> Add new warning message when output is plain text instead of object.

- powershell/cmdlets/class.ts
- powershell/generators/psm1.ts
- powershell/module/module-class.ts
This pull request primarily focuses on enhancing the telemetry and output sanitization in the `CmdletClass` and `NewModuleClass` within the `powershell/cmdlets/class.ts` and `powershell/module/module-class.ts` files respectively. The changes include the addition of a new method `NewImplementWriteObject`, inclusion of telemetry information, and sanitizing the output object.
Telemetry and Output Sanitization in `CmdletClass`:
* [`powershell/cmdlets/class.ts`]: Added a new method `NewImplementWriteObject` that includes two new `WriteObject` methods to sanitize the output before sending it to the pipeline.
* [`powershell/cmdlets/class.ts`]: Added telemetry information to the `CmdletClass` that includes sanitized properties and invocation name.
Telemetry and Output Sanitization in …
> Implement sanitizer handler for autorest

- common/config/rush/pnpm-lock.yaml
- powershell/plugins/create-commands-v2.ts
Developer needs to customize that operation and suppress error by disable-transform-identity-type-for-operation` in directive
> Throw error if current operation is mi operation but cannot be replaced by get+put

- powershell/plugins/create-commands-v2.ts
> Fix missing a space in command description

- powershell/generators/csproj.ts
- powershell/generators/gitignore.ts
- powershell/internal/project.ts
- powershell/resources/assets/build-module.ps1
original PR: #1376 
reverted by: #1380 
TODO: 1. insert header 2. update version during adapt parent
> generate assemblyinfo.cs for azure

- .github/workflows/test-emitter.yml
- .github/workflows/test-sdk.yml
This GitHub Action is going to replace the Azure Pipeline: https://github.com/Azure/autorest.powershell/blob/main/.azure-pipelines/test-sdk.yml
After this PR is merged, I'll delete https://github.com/Azure/autorest.powershell/blob/main/.azure-pipelines/test-sdk.yml.
Test PR: https://github.com/YanaXu/autorest.powershell/pull/1
> Move test-sdk.yml & test-emitter.yml from Azure Pipeline to GitHub Action

- powershell/plugins/sdk-create-inline-properties.ts
Fixed https://github.com/Azure/autorest.powershell/issues/1422
> sdk - fixed an additional property related issue

- powershell/cmdlets/class.ts
Link to issue: https://github.com/Azure/autorest.powershell/issues/1363
Regular expression issue, removed unexpected question mark in doc.
This PR removed question mark match in autorest powershell.
Tested in `Workloads/SAPVirtualInstance`, the generated doc in azure-powershell kept the question mark. 
And the only change between latest published version and this version is the question mark.
> Fix missing question mark

- packages/typespec-powershell/src/convertor/convertor.ts
- packages/typespec-powershell/src/utils/modelUtils.ts
This pull request improves how parameter and array schema descriptions are generated in the TypeSpec PowerShell converter, leading to more informative and user-friendly documentation output. The main changes focus on enhancing the fallback logic for descriptions when explicit documentation is missing.
**Improvements to description generation:**
* In `convertor.ts`, the logic for creating a parameter description now falls back to the schema's description if explicit documentation is unavailable, ensuring that parameters always have a meaningful description.
* In `modelUtils.ts`, array schema descriptions now use available documentation or, if missing, generate a description like "Array of [type name]", making array types clearer in generated docs.
> tsp - Add description for array body and path parameter if missing

- packages/typespec-powershell/src/convertor/convertor.ts
This pull request updates how parameters are handled when converting TypeSpec operations to PowerShell operations. The main change is to ensure that header parameters are included in the main operation parameters list, aligning their treatment with path and query parameters. This simplifies the parameter handling logic and removes redundant code that previously added header parameters separately to requests.
Parameter handling improvements:
* Header parameters are now included alongside path and query parameters in the main operation parameters list, ensuring consistent handling.
* Removed redundant code that separately added header parameters to the request, streamlining the conversion process.
> tsp - Added support for header parameter

- packages/typespec-powershell/src/convertor/convertor.ts
- packages/typespec-powershell/src/utils/modelUtils.ts
- tests-upgrade/tests-emitter/EmitterTest.ps1
This pull request introduces targeted improvements to the PowerShell emitter and related utilities. The main changes focus on ensuring that the correct client name overrides are applied for PowerShell, and updating test logic to better handle file selection during compilation.
**PowerShell-specific client name handling:**
* Updated both `getClientName` in `convertor.ts` and `getSchemaForModel` in `modelUtils.ts` to pass `"powershell"` as the override context, ensuring client name overrides are correctly applied for PowerShell scenarios. [[1]](diffhunk://#diff-deb3e8830d245343a9d4842c064b793ef5938fe39609ef552059d14b9b6a4be9L199-R199) [[2]](diffhunk://#diff-b14ca573b6245afb541400cac7bdbdd353e48bfdc0ff8254d5574da138dc0f07L746-R746)
**Test robustness improvements:**
* Modified the …
> tsp - Use 'powershell' for @clientname decorator

- packages/typespec-powershell/src/convertor/convertor.ts
- packages/typespec-powershell/src/utils/modelUtils.ts
This pull request introduces improvements and fixes to the schema generation and operation grouping logic in the TypeSpec PowerShell converter. The most significant changes enhance the handling of date-time encodings in schemas and improve the robustness of operation group mapping.
Schema generation improvements:
* Enhanced `getSchemaForType` to correctly handle model properties with date-time encodings, such as `rfc1123` and `rfc7231`, by setting a specific `format` in the schema when these encodings are detected. This ensures that the generated schema accurately reflects date-time encoding requirements.
* Updated the `mergeFormatAndEncoding` function to map specific encodings (like `rfc3339`, `unixTimestamp`, and `rfc7231`) to their appropriate schema formats, improving compatibility …
> tsp - Added suppport for rfc7231 and fixed an issue related to operationId
