src/csharp/lowlevel-generator/model/model-class.ts
src/csharp/lowlevel-generator/operation/method.ts
src/csharp/schema/byte-array.ts
src/csharp/schema/date-time.ts

See commits for details on fixes.

Evenmorefixes

---

extensions/powershell/resources/scripts/powershell/build-module.ps1
extensions/powershell/src/plugin-powershell.ts

Fixes: https://github.com/Azure/autorest/issues/3028
Fixes: https://github.com/Azure/autorest/issues/3023

Allows OutputType to be on the proxy functions. Fixed DefaultParameterSetName attribute.

---

extensions/powershell/src/generate-format-ps1xml.ts
extensions/powershell/src/plugin-powershell.ts

- Fixed the extra nesting for Header and Column items
- Added format.ps1xml to psd1

Psd1xml generator fix

---

extensions/csharp-v2/src/support/enum.ts
extensions/powershell/resources/scripts/powershell/build-module.ps1
extensions/powershell/src/cmdlet-class.ts
extensions/powershell/src/model-cmdlet.ts
extensions/powershell/src/powershell-declarations.ts
extensions/powershell/src/project.ts

Fixes: https://github.com/Azure/autorest/issues/3042

Enum argument completer

---

extensions/powershell/resources/assets/build-module.ps1
extensions/powershell/resources/runtime/GetProxyCmdlet.cs

Cleaned up build-module.ps1. Removed old proxy generation process. Fixed several issues with new proxy generator.
BTW, the proxy cmdlets previously took like 2-3 seconds to generate. This new generator takes like milliseconds.

Proxy generator fixes and usage

---

extensions/powershell/resources/runtime/GetProxyCmdlet.cs

Update default parameter set logic to use 'simple' parameter sets if they exist.

Proxy generator, smarter default param set

---

extensions/powershell/resources/runtime/GetProxyCmdlet.cs
extensions/powershell/src/cmdlet-class.ts

Changed default param set to be identified by variant if non-unnamed. Fixed HelpUri bug with special characters (newline).

Proxy generator fixes + helpuri

---

extensions/powershell/resources/assets/build-module.ps1
extensions/powershell/resources/runtime/NewProxyCmdlet.cs
extensions/powershell/resources/runtime/PsProxyOutputs.cs
extensions/powershell/src/cmdlet-class.ts

Fixes: https://github.com/Azure/autorest/issues/3122
Allows positional parameters to be written to the proxy cmdlets. Changed DefaultProfile to PSObject.
This finishes the last of the items in the issue above.

Proxy: Positional parameters + DefaultProfile PSObject

---

extensions/powershell/src/generators/psm1.ts
extensions/powershell/src/module-class.ts

Added support to load profiles via profile name.
This requires the latest `Az.Accounts` from https://github.com/fearthecowboy/azure-powershell/

ProfileName loading

---

extensions/powershell/resources/assets/build-module.ps1
extensions/powershell/resources/runtime/NewProxyCmdlet.cs
extensions/powershell/resources/runtime/NewTestStub.cs
extensions/powershell/resources/runtime/PsProxyOutputs.cs
extensions/powershell/resources/runtime/PsProxyTypes.cs
extensions/powershell/src/generators/psm1.custom.ts
extensions/powershell/src/generators/psm1.ts
extensions/powershell/src/plugin-powershell.ts
extensions/powershell/src/project.ts

This should be merged after https://github.com/Azure/autorest.powershell/pull/79
Fixes: https://github.com/Azure/autorest/issues/3162
Implements creating a custom script module (psm1) and loading the cmdlets from scripts as variants based on parameter sets in the scripts. This will also create the proxies for those scripts if there wasn't a pre-existing generated cmdlet.

Custom script loading

---

extensions/powershell/resources/assets/build-module.ps1
extensions/powershell/src/generators/psm1.custom.ts
extensions/powershell/src/generators/psm1.ts

Cleared implicit exports from both psm1s as to not cause duplication.

Custom loading fixes

---

extensions/powershell/src/cmdlet-class.ts
extensions/powershell/src/structural-modifier.ts

- Added the option to hide commands.
- Documentation: https://github.com/Azure/autorest/pull/3166
- Fixes: https://github.com/Azure/autorest/issues/3165

Added the option to hide commands.

---

extensions/powershell/resources/assets/build-module.ps1
extensions/powershell/resources/assets/generate-help.ps1
extensions/powershell/resources/assets/test-module.ps1
extensions/powershell/src/generators/psm1.ts
extensions/powershell/src/project.ts

Updated ps1 scripts to use config paths. Updated minimum version of Az.Accounts to be 1.3.1 (based on Mark's build).

Config paths + Az.Accounts version

---

extensions/powershell/resources/assets/build-module.ps1

Added -Docs flag to allow help documents generation for build-module.ps1.

Added -Docs flag

---

.gitignore
extensions/powershell/resources/assets/build-module.ps1
extensions/powershell/resources/built-time-cmdlets.csproj
extensions/powershell/resources/built-time-cmdlets.sln
extensions/powershell/resources/runtime/NewProxyCmdlet.cs
extensions/powershell/resources/runtime/NewTestStub.cs
extensions/powershell/resources/runtime/PsExtensions.cs
extensions/powershell/resources/runtime/SetPsd1Export.cs

Added a cmdlet at build-time to take the list of exported cmdlets (distinct) and write that list to the psd1. Added project/sln for further build-time cmdlet development.

Psd1 CmdletsToExport list

---

extensions/powershell/src/cosmetic-modifier.ts
extensions/powershell/src/plugin-namer.ts
extensions/remodeler/src/plugin-create-inline-properties.ts

- Make sure to pull this changes in submodule: https://github.com/Azure/perks/compare/virtual-prop-update?expand=1

Virtual properties/parameters update to modifiers.

---

extensions/powershell/generators/psm1.ts
extensions/powershell/project.ts

Made module loading in psm1 write to information stream. Added verbose message for cmdlet renaming when combining noun and noun-prefix.

Various changes 1

---

extensions/powershell/generators/nuspec.ts
extensions/powershell/resources/assets/.gitattributes

Added .gitattributes for correctly assessing generated line endings. Fixed nuspec gen not using minimum accounts version.

Misc fixes

---

extensions/powershell/project.ts
extensions/remodeler/src/remodeler.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/174

Added cosumed profiles list to codemodel, and updated project to use that list

---

extensions/powershell/module-class.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/150

Added 'Name' property to module.cs for non-azure

---

extensions/powershell/resources/assets/check-dependencies.ps1
extensions/powershell/resources/assets/generate-help.ps1
extensions/powershell/resources/assets/test-module.ps1

Removed the progress indicator for check-dependencies.ps1, generate-help.ps1, and test-module.ps1.

Remove progress indicator

---

extensions/powershell/cosmetic-modifier.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/230

Update modifiers: Now able to select/scope explicitly by parameter, command, model, etc

---

extensions/powershell/resources/runtime/PsProxyTypes.cs

Keyed parameter determination on parameter sets existing instead of if it is a script cmdlet vs C# cmdlet.

Parameter determination fix

---

extensions/powershell/generators/script-cmdlet.ts
extensions/powershell/resources/runtime/PsProxyOutputs.cs
extensions/powershell/resources/runtime/PsProxyTypes.cs

Added PositionalBinding so that position numbers are not created for script cmdlets by default.

PositionalBinding fix

---

extensions/powershell/cosmetic-modifier.ts
extensions/powershell/plugin-namer.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/254
Fixes: https://github.com/Azure/autorest.powershell/issues/255

Naming updates: singularize params and directive to clear aliases

---

extensions/powershell/generators/psm1.custom.ts
extensions/powershell/generators/psm1.internal.ts
extensions/powershell/generators/psm1.ts

Allows the internal module to load profiles of internal cmdlets. Cleaned up regions for psm1 files to only have a single Generated region (better support for future changes).

Internal module loading fix

---

extensions/powershell/generators/psm1.custom.ts
extensions/powershell/generators/psm1.internal.ts
extensions/powershell/generators/psm1.ts
extensions/powershell/resources/runtime/ExportProxyCmdlet.cs
extensions/powershell/resources/runtime/ExportTestStub.cs
extensions/powershell/resources/runtime/PsProxyOutputs.cs
extensions/powershell/resources/runtime/PsProxyTypes.cs

This makes it so that these attributes are output to Exports/Internal:
- Profile
- Description
- Category (for parameters)
In addition, I removed the comment-based help for parameters, and instead am using `HelpMessage` for the Parameter attribute.

Export attribute sync

---

extensions/csharp-v2/exports.ts
extensions/csharp-v2/schema/array.ts
extensions/powershell/cmdlet-class.ts
extensions/powershell/resources/runtime/PsExtensions.cs
extensions/powershell/resources/runtime/PsProxyOutputs.cs

Allows arrays of enums to have ArgumentCompleter of the enum type.

Enum completer for arrays

---

extensions/powershell/modifiers.ts

Examples:
```
directive:
- where: 
verb: Get
set:
alias: ${verb}-Az${subject-prefix}INSERTION${subject}
- where: 
verb: New
set:
alias: 
- ${verb}-Az${subject-prefix}INSERTION1${subject}
- ${verb}-Az${subject-prefix}INSERTION2${subject}
``` 
Log of changes in a sample service:
```
VERBOSE: [DIRECTIVE] Added alias Get-AzAppINSERTIONConfigurationStore to command Get-AppConfigurationStore_List.
VERBOSE: [DIRECTIVE] Added alias Get-AzAppINSERTIONConfigurationStore to command Get-AppConfigurationStore_List1.
VERBOSE: [DIRECTIVE] Added alias Get-AzAppINSERTIONConfigurationStore to command Get-AppConfigurationStore_Get.
VERBOSE: [DIRECTIVE] Added alias Get-AzAppINSERTIONConfigurationStore to command Get-AppConfigurationStore_GetViaIdentity.
VERBOSE: [DIRECTIVE] Added alias …
```

modifiers: added support to modify aliases in bulk using parts of command

---

extensions/powershell/resources/runtime/PsExtensions.cs
extensions/powershell/resources/runtime/PsHelpers.cs

Clean up script invoking implementation. Now allows ScriptBlocks to be directly run.

Script invoke cleanup

---

extensions/powershell/modifiers.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/301

fix to bulk aliases

---

.vscode/launch.json
extensions/powershell/plugin-namer.ts
extensions/powershell/test/noun-cleaning.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/310

Fix to psnamer's sequential-duplicates remover

---

extensions/csharp-v2/csharp-declarations.ts
extensions/csharp-v2/model/model-class.ts
extensions/powershell/resources/runtime/PsAttributes.cs

fixes: https://github.com/Azure/autorest.powershell/issues/303
addresses: https://github.com/Azure/autorest.powershell/issues/315

Added attributes for default format support

---

extensions/powershell/plugin-namer.ts
extensions/remodeler/plugin-create-inline-properties.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/326

Fix param name

---

extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportFormatPs1xml.cs
extensions/powershell/resources/runtime/BuildTime/Models/PsFormatTypes.cs
extensions/powershell/resources/runtime/BuildTime/PsAttributes.cs

Updated the format.ps1xml generation logic to allow for configuration and for an updated default inclusion and ordering logic.

Format using attributes

---

extensions/powershell/modifiers.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/356
```
- where:
parameter-name: (.*)VirtualMachine(.*)
set:
alias: $1VM$2
```

Use parameter-name regex capture groups in alias

---

extensions/powershell/modifiers.ts

Fixes: https://github.com/Azure/autorest.powershell/issues/353

fixed bug - property rename from configuration

---

extensions/powershell/resources/runtime/BuildTime/Cmdlets/ExportTestStub.cs

Added filepath to the test stubs for where the recording goes and is named.

Test recording path

---

extensions/powershell/resources/runtime/BuildTime/Models/PsProxyTypes.cs

Also fixed a minor bug with simple type resolution.

Implements using ExportAs at build time.

---

extensions/powershell/generators/psm1.internal.ts
extensions/powershell/generators/psm1.ts
extensions/powershell/resources/assets/test-module.ps1
extensions/powershell/resources/runtime/HttpPipelineMocking.ps1

Added defaultparameters to the psm1 for Azure (just SubscriptionId). Cleaned up HttpPipelineMocking.ps1 (whitespace mainly). Added a few switches to test-module.ps1 for setting test mode.

Test cleanup and defaultparameters for SubscriptionId

---

extensions/csharp-v2/resources/runtime/csharp/client/UndeclaredResponseException.cs
extensions/powershell/cmdlet-class.ts

@kenal-microsoft   -- I've cleaned it a smidgen -- does this work for you?

Refinement of Error Code refactoring

---

extensions/csharp-v2/schema/byte-array.ts
extensions/powershell/README.md
extensions/powershell/cmdlet-class.ts
extensions/powershell/modifiers.ts
extensions/powershell/namespaces/model-extensions.ts
extensions/powershell/project.ts
extensions/remodeler/plugin-create-inline-properties.ts

Plus:
- add base64 byte array fix for cormac
-  new-transform step after modeler

Add By reference support for network

---

powershell/cmdlets/class.ts
powershell/llcsharp/operation/method.ts
powershell/resources/runtime/csharp/client/UndeclaredResponseException.cs

fix LRO again for network, 
add extra check for nested error data in unexpected response exception, 
fix select-object pipelinestoppedexecption

Fixes for preview

---

powershell/generators/nuspec.ts
powershell/generators/psm1.ts
powershell/resources/built-time-cmdlets.csproj
powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs

1. Load Az.Accounts first, #https://github.com/Azure/autorest.powershell/issues/525
2. Combine the cmdlets files in exports folder into one file for signing, #https://github.com/Azure/autorest.powershell/issues/524
3. Fix build-time-cmdlets.csproj caused by code refactoring,

Fixed a few issues

---

powershell/resources/assets/check-dependencies.ps1
powershell/resources/assets/test-module.ps1
powershell/resources/assets/test/loadEnv.ps1
powershell/resources/psruntime/BuildTime/Cmdlets/ExportTestStub.cs

https://github.com/Azure/autorest.powershell/issues/512

Add support for key/value storage and random generation in tests 

---

powershell/cmdlets/class.ts
powershell/module/module-class.ts
powershell/resources/runtime/csharp/client/CmdInfoHandler.cs

added telemetry:
```
x-ms-request-client-id:          GUID
CommandName:                    Get-AzAks
FullCommandName:              Get-AzAks_List
ParameterSetName:              
```

add missing server side telemetry

---

powershell/resources/psruntime/BuildTime/Cmdlets/ExportPsd1.cs

https://github.com/Azure/autorest.powershell/issues/514

handle 'preview' module versions in psd1 and nupkg generation

---

powershell/resources/runtime/csharp/client/UndeclaredResponseException.cs
powershell/resources/runtime/csharp/pipeline/PipelineMocking.cs

https://github.com/Azure/autorest.powershell/issues/551 and https://github.com/Azure/autorest.powershell/issues/544

Request with content should be cloned before sending

---

powershell/llcsharp/schema/date-time.ts

https://github.com/Azure/autorest.powershell/issues/559

Fixed the serialization issue of datetime

---

powershell/llcsharp/operation/method.ts
powershell/llcsharp/project.ts

Add a configuration for correcting identity, https://github.com/Azure/azurestack-powershell-pr/issues/80

---

powershell/resources/psruntime/HttpPipeline.cs

typo in comment

---

tests-upgrade/AutoRestUpgradeTest.ps1

Change the AutoRestUpgrade.ps1 for pipeline.

Change the AutoRestUpgrade.ps1 for pipeline

---

tests-upgrade/AutoRestUpgradeTest.ps1

Add a function to determine whether each folder is in the blacklist.

Fix the BlackList issue

---

powershell/llcsharp/operation/method.ts
powershell/plugins/cs-namer-v2.ts
powershell/plugins/plugin-tweak-m4-model.ts

1. Fix url
2. Make enum name same as m3
3. Make api version same as m3

Fix some issues

---

powershell/generators/gitignore.ts

Ignore tools

---

powershell/plugins/create-commands-v2.ts

Add support support for API, whose request body is just an object without specifying any details

---

powershell/llcsharp/operation/method.ts

- Fix #610
- Fix #608
- Combine with Azure/azure-powershell/pull/13612 , we can have full debug log of polling requests and response (including status, header, body). Preview the results in #608

start polling when 200 OK; write polling req/res to debug log

---

powershell/plugins/plugin-create-inline-properties.ts

Fix https://github.com/Azure/autorest.powershell/issues/745, clean null properties

---

docs/readme.md

Typo in link to github in 'filing bugs'

Fix github URL

---

common/scripts/install-run.js
rush.json

The upgrade is for security reasons.

upgrade rush to 5.50.0, pnmp to 6.10.3

---

powershell/cmdlets/class.ts
powershell/resources/psruntime/MessageAttribute.cs

Change data format to mm/dd/yyyy

Change date format for breaking change

---

powershell/llcsharp/model/model-class.ts
powershell/llcsharp/project.ts
powershell/plugins/plugin-tweak-model.ts

Add ResourceGroupName for returned object
- Add a flag in directive to show whether add ResourceGroupName for returned object
- If resourcegroup-append: true in directive and returned object contains property Id, append ResourceGroupName as its public property

Add ResourceGroupName for returned object

---

powershell/package.json
powershell/resources/assets/build-module.ps1
powershell/resources/assets/generate-help.ps1
powershell/resources/psruntime/BuildTime/Cmdlets/ExportHelpMarkdown.cs
powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
powershell/resources/psruntime/BuildTime/MarkdownRenderer.cs
powershell/resources/psruntime/BuildTime/Models/PsHelpMarkdownOutputs.cs
powershell/resources/psruntime/BuildTime/Models/PsHelpTypes.cs
powershell/resources/psruntime/BuildTime/Models/PsMarkdownTypes.cs
powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs

Provide flag `-ExcludeExampleTemplates` to control whether or not example templates are included in MarkDown docs and ProxyCmdletDefinitions.ps1.
Currently, example templates are always emitted into the documentation file such as:-
`````
The set of appointments of this business in a specified date range.
Read-only.
Nullable.
```powershell
PS C:\> {{ Add code here }}
{{ Add output here }}
```
{{ Add description here }}
```powershell
PS C:\> {{ Add code here }}
{{ Add output here }}
```
{{ Add description here }}
`````
And in ProxyCmdletDefinitions.ps1
```
<#
.Synopsis
All the appointments of this business.
Read-only.
Nullable.
.Description
All the appointments of this business.
Read-only.
Nullable.
.Example
PS C:\> {{ Add code here }}
{{ Add output here }}
.Example
PS C:\> {{ Add code here …
```

Provide flag `-ExcludeExampleTemplates` to control emission of Example Templates

---

powershell/generators/psm1.ts
powershell/internal/project.ts
powershell/module/module-class.ts
powershell/plugins/plugin-tweak-m4-model.ts

1. Add api version for dict ref as parents of an object
2. rename endpointkeyname to endpointresourceidkeyname
3. endpointsuffixkeyname should be optional

Add api version for dict ref as parents of an object

---

powershell/resources/psruntime/DictionaryExtensions.cs
powershell/resources/runtime/csharp/json/Customizations/IJsonSerializable.cs

Support following case
```
"xxx": {
"type": "object",
"additionalProperties":true
}
```

Fix object with additional properties

---

powershell/enums/namespace.ts

refer to https://github.com/Azure/autorest.powershell/issues/784 for details.

put enum value in single quotes for completer

---

docs/samples/timeswire/readme.md
docs/samples/timeswire/timeswire.yaml
docs/samples/xkcd/readme.md
powershell/llcsharp/schema/array.ts
samples/TimesWire/timeswire.yaml

Refer to https://github.com/Azure/autorest.powershell/issues/827 for details.

update sample related docs and fix a query parameter related issue

---

powershell/resources/psruntime/BuildTime/Cmdlets/GetScriptCmdlet.cs

Output error message in GetScriptCmdlet.cs

---

.azure-pipelines/daily-build.yml

Test run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1195156&view=results

Update daily-build.yml for Azure Pipelines

---

powershell/llcsharp/model/model-class-serializer.ts
powershell/llcsharp/operation/method.ts
powershell/resources/psruntime/TypeConverterExtensions.cs

1. When piping, Id validation is changed to case insensitive
2. Fixed issue 858

Make uri validatation case insensitive and fixed issue 858

---

powershell/resources/runtime/csharp/json/Customizations/IJsonSerializable.cs

This PR applies changes made in https://github.com/Azure/autorest.powershell/pull/868 to the `MSgraph` branch as well.

Serialize `DictionaryEntry` types as value type.

---

powershell/resources/runtime/csharp/json/Customizations/IJsonSerializable.cs
powershell/resources/runtime/csharp/json/Nodes/JsonNumber.cs

This PR fixes https://github.com/Azure/autorest.powershell/issues/772 by applying changes made in the `main` branch to `msgraph` branch.

Make floating point types culture invariant.

---

powershell/internal/project.ts
powershell/resources/psruntime/BuildTime/Models/PsProxyTypes.cs

root-module-name will be used in help link in comment based help and markdown help

Add configuration root-module-name,

---

docs/samples/xkcd/readme.md
samples/Xkcd/xkcd.yaml

Since the sample was written about three years ago, some of the content is out-date and need to be updated accordingly.

Update xkcd sample

---

powershell/llcsharp/model/model-class.ts
powershell/llcsharp/project.ts
powershell/plugins/modifiers-v2.ts
powershell/utils/schema.ts

Currently table view support for resouregroupname does not work through directive if it is added through resourcegroup-append.
Fixed https://github.com/Azure/autorest.powershell/issues/886.

Add table view support for resourcegroupname 

---

powershell/module/module-class.ts

The commit is to fix the issue that proxy credentials do not work.
Related technical materials are as below.
https://docs.microsoft.com/en-us/dotnet/api/system.net.webproxy.usedefaultcredentials?view=net-6.0
https://docs.microsoft.com/en-us/dotnet/api/system.net.webproxy.credentials?view=net-6.0

Add support for proxy credentials

---

powershell/llcsharp/model/model-class.ts

Match resource id case insensitive when extracting resource group from id

Match resource id case insensitive

---

powershell/resources/psruntime/BuildTime/Models/PsHelpMarkdownOutputs.cs
powershell/resources/psruntime/BuildTime/Models/PsHelpTypes.cs
powershell/resources/psruntime/BuildTime/Models/PsMarkdownTypes.cs

Modify example template

---

powershell/resources/assets/create-model-cmdlets.ps1

Fixed https://github.com/Azure/autorest.powershell/issues/908

Fix an enum array related issue in create-model-cmdlet

---

powershell/cmdlets/class.ts
powershell/internal/name-inferrer.ts
powershell/plugins/create-commands-v2.ts
powershell/plugins/plugin-create-inline-properties.ts

Fixed some issues for msgraph team

---

powershell/llcsharp/enums/enum.ts
powershell/llcsharp/model/model-class-json.ts

Fix: https://github.com/Azure/autorest.powershell/issues/843

Fix inappropriate usages of tags

---

.default-eslintrc.yaml
common/config/rush/pnpm-lock.yaml
powershell/cmdlets/class.ts
powershell/cmdlets/namespace.ts
powershell/enums/namespace.ts
powershell/generators/psm1.ts
powershell/internal/project.ts
powershell/llcsharp/enums/enum.ts
powershell/llcsharp/model/interface.ts
powershell/llcsharp/model/model-class-serializer.ts
powershell/llcsharp/model/model-class.ts
powershell/llcsharp/operation/method.ts
powershell/llcsharp/schema/date-time.ts
powershell/llcsharp/schema/password.ts
powershell/llcsharp/schema/primitive.ts
powershell/llcsharp/schema/string.ts
powershell/models/model-extensions.ts
powershell/module/module-class.ts
powershell/package.json
powershell/plugins/create-commands-v2.ts
powershell/plugins/cs-namer-v2.ts
powershell/plugins/modifiers-v2.ts
powershell/plugins/plugin-tweak-m4-model.ts
powershell/plugins/plugin-tweak-model-azure-v2.ts
powershell/plugins/plugin-tweak-model.ts
powershell/utils/powershell-comment.ts

Make following update   
"@typescript-eslint/eslint-plugin": "~5.29.0",
"@typescript-eslint/parser": "~5.29.0"

update lint related package and fix some lint issues

---

powershell/cmdlets/class.ts
powershell/plugins/create-commands-v2.ts

Fixed https://github.com/Azure/autorest.powershell/issues/955 and https://github.com/Azure/autorest.powershell/issues/962

Fixed issue 955 and 962

---

docs/directives.md

See the PR for details of the docs added

Add docs for custom input parameter

---

powershell/autorest-configuration-for-sdk.md
powershell/autorest-configuration.md
powershell/cmdlets/class.ts
powershell/llcsharp/schema/schema-resolver.ts
powershell/main.ts
powershell/package.json
powershell/plugins/create-commands-v2.ts
powershell/plugins/powershell-v2.ts
powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-generate.ts
powershell/plugins/sdk-tweak-model.ts
powershell/readme.md
powershell/resources/templates/azureMethod.ejs
powershell/resources/templates/azureMethodGroup.ejs
powershell/resources/templates/azureServiceClient.ejs
powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/extensions.ejs
powershell/resources/templates/method.ejs
powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/methodGroup.ejs
powershell/resources/templates/methodGroupInterface.ejs
powershell/resources/templates/model.ejs
powershell/resources/templates/serviceClientBody.ejs
powershell/resources/templates/serviceClientInterface.ejs
powershell/sdk/project.ts
powershell/sdk/state.ts
powershell/sdk/utility.ts
powershell/utils/SdkModel.ts

Track1sdk initial support for a simple get API

---

powershell/package.json
powershell/plugins/powershell-v2.ts

This will fix the issue that we can not execute eslint

Upgrade typescript to ~4.3.0

---

powershell/cmdlets/class.ts
powershell/llcsharp/clientruntime.ts
powershell/llcsharp/operation/method.ts
powershell/resources/runtime/csharp/pipeline/Events.cs

Visual effects on `New-AzDatabricksWorkspace`.

Display progress bar for long running operations

---

powershell/autorest-configuration.md
powershell/cmdlets/class.ts
powershell/internal/powershell-declarations.ts
powershell/llcsharp/schema/schema-resolver.ts
powershell/llcsharp/schema/uri.ts
powershell/plugins/create-commands-v2.ts
powershell/plugins/plugin-create-inline-properties.ts
powershell/plugins/plugin-tweak-model.ts
powershell/resources/psruntime/Attributes/ExternalDocsAttribute.cs
powershell/resources/psruntime/BuildTime/Models/PsMarkdownTypes.cs
powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
powershell/resources/psruntime/BuildTime/Models/PsProxyTypes.cs
powershell/utils/components.ts

Move https://github.com/Azure/autorest.powershell/pull/1004 to develop branch

Support ExternalDocs for autorest.powershell

---

powershell/module/module-class.ts
powershell/package.json

Fixed issue https://github.com/Azure/autorest.powershell/issues/1019

Need to add the parameter ExtensibleParameters as well when azure is not set

---

powershell/autorest-configuration-for-sdk.md
powershell/main.ts
powershell/plugins/powershell-v2.ts
powershell/plugins/sdk-create-inline-properties.ts
powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-generate.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/azureMethodGroup.ejs
powershell/resources/templates/azureServiceClient.ejs
powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/extensions.ejs
powershell/resources/templates/method.ejs
powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/methodGroup.ejs
powershell/resources/templates/methodGroupInterface.ejs
powershell/resources/templates/model.ejs
powershell/resources/templates/serviceClientBody.ejs
powershell/resources/templates/serviceClientInterface.ejs
powershell/sdk/project.ts
powershell/sdk/utility.ts
powershell/utils/SdkModel.ts
powershell/utils/schema.ts

1. Support flatten (x-ms-client-flatten,  payload-flattening-threshold)
2. Support API with a request body, e.g. PUT/Post
3. Support Delete API

Sdk - add flatten/put/delete support

---

powershell/cmdlets/class.ts
powershell/llcsharp/operation/method.ts

```powershell
$job = New-AzDatabricksWorkspace -ResourceGroupName yemingtemp -Name yeming111804 -Location eastus2 -AsJob
$job | Wait-Job
$job.Progress
```
You can see the last progress info is correctly set to "Finished".

Set final state of progress bar

---

powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/model.ejs

1. re-order parameters to align with track1 sdk generator
2. Fixed some minor issues

sdk - re-order parameters to align with track1 sdk generator

---

powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/methodBodyRestCall.ejs

1. Array of primitive type should have ?
2. Fixed a default type related issue
3. Fixed a prefix related issue

sdk - Fixed several issues

---

powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/model.ejs
powershell/sdk/utility.ts
powershell/utils/schema.ts

Fixed failed case datamodels-datatypes-date and datamodels-datatypes-datetime

sdk - Fixed several issues related to choice/sealedchoice

---

powershell/plugins/sdk-create-inline-properties.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/model.ejs
powershell/sdk/utility.ts
tests-upgrade/tests-sdk1-support/component-param-grouping/csharp/ParameterGroupingOperations.cs
tests-upgrade/tests-sdk1-support/configuration.json

Add support for [x-ms-parameter-grouping](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-parameter-grouping).
And related test case is component-param-grouping.

sdk - Add support for x-ms-parameter-grouping

---

powershell/resources/templates/model.ejs
powershell/sdk/utility.ts

The constant is required property, whose type is enum with one value.

sdk - Add support for const in model

---

powershell/plugins/sdk-create-inline-properties.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/methodBodyRestCall.ejs
powershell/sdk/utility.ts
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/DatabricksClient.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/HeaderOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/HeaderOperationsExtensions.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/IDatabricksClient.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/IHeaderOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/ISkipUrlEncodingOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/IXMsClientRequestIdOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/Models/HeaderCustomNamedRequestIdHeadHeaders.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/Models/HeaderCustomNamedRequestIdHeaders.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/SdkInfo_DatabricksClient.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/SkipUrlEncodingOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/SkipUrlEncodingOperationsExtensions.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/XMsClientRequestIdOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/XMsClientRequestIdOperationsExtensions.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/swagger.json
tests-upgrade/tests-sdk1-support/configuration.json

1. Add support for header response
2. Adjust some code generated by autorest.csharp in component-param-specialproperties/csharp.

sdk - Add support for header response

---

powershell/plugins/sdk-create-inline-properties.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/methodBodyRestCall.ejs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/HeaderOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/HeaderOperationsExtensions.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/csharp/IHeaderOperations.cs
tests-upgrade/tests-sdk1-support/component-param-specialproperties/swagger.json
tests-upgrade/tests-sdk1-support/configuration.json

Add support for [x-ms-odata](https://github.com/stankovski/AutoRest/blob/master/Documentation/swagger-extensions.md#x-ms-odata)

sdk - Add support for x-ms-odata

---

powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/serviceClientBody.ejs

Fixed 3 issues
- Added special handle when nextLinkName is null. No need {OperationName}Next method. 
- Fixed c# parameter comment issue in client template
- Removed query parameters from pageable method body

[x-ms-pageable] Special handle when nextLinkName is null

---

powershell/plugins/sdk-cs-namer.ts

valuetype -> valuetype?
any -> object

polish value type of dictionary

---

powershell/plugins/sdk-cs-namer.ts
tests-upgrade/tests-sdk1-support/configuration.json

1. Fixed test case component-param-additional
2. Fixed a naming related issue

Sdk- Fixed test case component-param-additional

---

powershell/plugins/sdk-generate.ts
powershell/resources/templates/methodBodyRestCall.ejs

do not generate models for 'x-ms-external',
generate exception code for 'x-ms-request-id'

x-ms-external and x-ms-request-id

---

powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/model.ejs
powershell/resources/templates/serviceClientBody.ejs

1. Escape related output for comments
2. Fixed an issue related to model
3. Fixed an issue related to argument order

sdk - Fixed a few issues

---

powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/model.ejs
powershell/sdk/utility.ts
tests-upgrade/tests-sdk1-support/basic-polymorphism/csharp/Models/IoTHubEventSourceResource.cs

1. Use virtualpropery.name to replace virtualpropery.property.default.language.name to avoid potential naming conflicts
2. Fixed a validation related issue

sdk - Fixed a few issues related to validation and naming

---

powershell/plugins/sdk-create-inline-properties.ts
powershell/resources/templates/model.ejs

1. Issue#1 is related to enum
2. Issue#2 is related to reserved C# key word

sdk - Fixed two minor issues

---

powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/longRunningOperationMethod.ejs
powershell/resources/templates/method.ejs
powershell/resources/templates/methodGroupInterface.ejs
powershell/resources/templates/model.ejs
powershell/resources/templates/serviceClientBody.ejs

For constant parameter/property, we should not generate comments for them.

sdk - remove const parmater/property from comments

---

powershell/plugins/sdk-cs-namer.ts
powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/model.ejs
powershell/sdk/utility.ts

Add support for integer with 64 precision

sdk - Add support for long

---

powershell/plugins/sdk-tweak-model.ts

For following case, we need to generate a response with bool type.
1. No response body or response header
2. Two responses and one of them is 404

sdk - Add support for head request without response and return 404

---

powershell/plugins/sdk-create-inline-properties.ts
powershell/resources/templates/methodBodyRestCall.ejs

1. Add support for payload-flattening-threshold
2. Fixed a minor issue

sdk - Add support for payload-flattening-threshold

---

powershell/autorest-configuration.md

Protect UX folder when generate code

Protect UX folder

---

docs/samples/xkcd/xkcd.yaml
powershell/cmdlets/class.ts
powershell/generators/script-cmdlet.ts
powershell/resources/assets/build-module.ps1
powershell/resources/assets/tools/Resources/custom/New-AzDeployment.ps1
powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
powershell/resources/psruntime/MessageAttributeHelper.cs

Changes include:
1.  Clean model cmdlet folder when regenerate
2.  Add warning message for -DefaultProfile

Add warning message for -DefaultProfile

---

powershell/cmdlets/class.ts
powershell/internal/project.ts
powershell/llcsharp/schema/array.ts
powershell/llcsharp/schema/fixed-array.ts
powershell/llcsharp/schema/schema-resolver.ts
powershell/resources/assets/create-model-cmdlets.ps1
powershell/resources/psruntime/TypeConverterExtensions.cs
powershell/resources/runtime/csharp/json/Nodes/Collections/XNodeArray.cs

v4 - intial support for nonfixed array

---

powershell/resources/assets/build-module.ps1
powershell/resources/assets/check-dependencies.ps1
powershell/resources/assets/export-surface.ps1
powershell/resources/assets/generate-help.ps1
powershell/resources/assets/generate-portal-ux.ps1
powershell/resources/assets/run-module.ps1
powershell/resources/assets/test-module.ps1

1. Should be NotIsolated instead of Isolated for all related ps1 script
2. Only singular the final word in group for cmdlet name

V4/fix - should be NotIsolated instead of Isolated

---

powershell/llcsharp/model/model-class.ts

The pr fixed the issue https://github.com/Azure/autorest.powershell/issues/1041

v4 - Inherited internal property should be internal instead of public

---

powershell/llcsharp/model/model-class.ts

The PR fixed the issue https://github.com/Azure/autorest.powershell/issues/1151.

v4 - Polymorphic member should be public in a model

---

.default-eslintrc.yaml
powershell/cmdlets/class.ts
powershell/cmdlets/namespace.ts
powershell/llcsharp/operation/api-class.ts
powershell/llcsharp/operation/method.ts
powershell/llcsharp/schema/array.ts
powershell/llcsharp/schema/date-time.ts
powershell/llcsharp/schema/duration.ts
powershell/llcsharp/schema/fixed-array.ts
powershell/llcsharp/schema/primitive.ts
powershell/llcsharp/schema/string.ts
powershell/plugins/create-commands-v2.ts
powershell/plugins/cs-namer-v2.ts
powershell/plugins/modifiers-v2.ts
powershell/plugins/sdk-tweak-model.ts
powershell/sdk/utility.ts
powershell/utils/http-operation.ts

Most of the issues are resolved by running `rush fix`

v4 - Fixed code style relevant issues

---

powershell/cmdlets/class.ts
powershell/llcsharp/clientruntime.ts
powershell/plugins/modifiers-v2.ts
powershell/resources/psruntime/MessageAttribute.cs
powershell/resources/psruntime/Properties/Resources.Designer.cs
powershell/resources/psruntime/Properties/Resources.resx

Make az version and module version required

Update breaking change attribute

---

powershell/cmdlets/class.ts
powershell/llcsharp/clientruntime.ts
powershell/plugins/modifiers-v2.ts
powershell/resources/psruntime/MessageAttribute.cs
powershell/resources/psruntime/Properties/Resources.Designer.cs
powershell/resources/psruntime/Properties/Resources.resx

Make az version and module version required

Update breaking change attribute to make version required

---

powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/model.ejs
powershell/sdk/utility.ts

1. Enum is value type, should not check null
2. model with x-ms-azure-resource should not validate parent
3. For next page operation, no need to handle const parameters

Fixed two issues related to SDK

---

powershell/plugins/sdk-create-inline-properties.ts
powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/model.ejs
powershell/sdk/project.ts
powershell/sdk/utility.ts

- Add useDateTimeOffset support, which could be set in readme.md
- nullable support, nullable is default true, if false is set, '?' should be removed for primitive data type

Add support for useDateTimeOffset and nullable

---

powershell/cmdlets/class.ts
powershell/plugins/modifiers-v2.ts
powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
powershell/resources/psruntime/MessageAttribute.cs
powershell/resources/psruntime/MessageAttributeHelper.cs
powershell/resources/psruntime/Properties/Resources.Designer.cs
powershell/resources/psruntime/Properties/Resources.resx

Support add estimated-ga-date for preview cmdlet

---

powershell/cmdlets/class.ts
powershell/plugins/modifiers-v2.ts
powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
powershell/resources/psruntime/MessageAttribute.cs
powershell/resources/psruntime/MessageAttributeHelper.cs
powershell/resources/psruntime/Properties/Resources.Designer.cs
powershell/resources/psruntime/Properties/Resources.resx

Move https://github.com/Azure/autorest.powershell/pull/1200 to v3

Support add estimated-ga-date for preview cmdlet (#1200)

---

powershell/plugins/sdk-cs-namer.ts
powershell/resources/templates/longRunningOperationMethod.ejs
powershell/resources/templates/method.ejs
powershell/resources/templates/methodBodyRestCall.ejs

1. For polling call, request body is not needed
2. Fixed a naming issue related to enum

Fixed several issues related to SDK

---

powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-generate.ts
powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/extensions.ejs
powershell/resources/templates/longRunningOperationMethod.ejs
powershell/resources/templates/method.ejs
powershell/resources/templates/methodBodyRestCall.ejs

In the case that operation does not belong to any group, there will be generated in the client instead of an operation group. And in this case we will need to generate extension for them as client extension

Generate extension for client there are API without group

---

powershell/plugins/sdk-tweak-model.ts
powershell/resources/templates/longRunningOperationMethod.ejs
powershell/resources/templates/method.ejs
powershell/resources/templates/methodBodyRestCall.ejs

1. remove read only properties from operation API
2. should not assign value to constant enum
3. Fixed serialization issue for client-request-id parameter with type uuid
4. Clean some redundant comments for parameters.

Fixed a few bugs related to readonly parameter and const enum

---

powershell/plugins/sdk-create-inline-properties.ts
powershell/resources/templates/methodBodyRestCall.ejs
powershell/sdk/utility.ts

1. Should not flatten polymorphic class
2. Should not check null for required value type

Fixed two issues related to polymorphic class flattening and value type

---

powershell/resources/templates/enum.ejs
powershell/resources/templates/extensionMethod.ejs
powershell/resources/templates/methodBodyRestCall.ejs
powershell/resources/templates/methodGroupInterfaceBody.ejs
powershell/sdk/utility.ts

1. Remove incorrect parameter comments
2. Fixed an enum related issue whose value starts with _
3. Fixed a name conflict issue

Fixed three SDK issues

---

powershell/sdk/utility.ts

The change only take effective on path/query parameters

Use DateTimeRfc1123JsonConverter for datetime with format date-time-rfc1123

---

powershell/resources/assets/build-module.ps1
powershell/resources/assets/generate-help.ps1
powershell/resources/psruntime/BuildTime/Cmdlets/ExportHelpMarkdown.cs
powershell/resources/psruntime/BuildTime/Cmdlets/ExportProxyCmdlet.cs
powershell/resources/psruntime/BuildTime/MarkdownRenderer.cs

Move https://github.com/Azure/autorest.powershell/pull/1164 to autorest/powershell v3

Remove complex interface information from help markdown in v3

---

powershell/plugins/sdk-cs-namer.ts
powershell/resources/templates/methodBodyRestCall.ejs

1. object array 
2. remove unneeded client

 Fixed two issues, 1. object array 2. remove unneeded client

---

powershell/llcsharp/model/model-class-json.ts

This PR is to fix the issue https://github.com/Azure/autorest.powershell/issues/1258.

Fixed a de-serialize related issue

---

powershell/llcsharp/model/model-class.ts

Fixed https://github.com/Azure/autorest.powershell/issues/1271

Fixed an issue relevant to polymorphism

---

powershell/resources/assets/generate-portal-ux.ps1

Fix the issue that generate-portal-ux.ps1 may fail when process the internal cmdlets

Fix the issue that generate-portal-ux.ps1 may fail when process the internal cmdlets

---

powershell/plugins/create-commands-v2.ts

To fix the scenario where we don't have put or get operation to replace patch operation

Add patch back if no get or put

---

powershell/generators/psm1.ts
powershell/resources/assets/test-module.ps1
powershell/resources/assets/test/loadEnv.ps1
powershell/resources/psruntime/BuildTime/Cmdlets/ExportTestStub.cs
powershell/resources/psruntime/BuildTime/Models/PsProxyOutputs.cs
powershell/resources/utils/Get-SubscriptionIdTestSafe.ps1

This reverts commit 7359d8e03ebc9ea37c81f9b336d8614bdd486fbc.

Revert "Add function in psm1 to mock subscription id (#1318)"

---

powershell/plugins/create-commands-v2.ts

Fix global match

---

powershell/cmdlets/class.ts
powershell/internal/project.ts
powershell/resources/assets/build-module.ps1

Sync after build in build-module.ps1 to v3

Added after build task in build-module generation (#1331)

---

powershell/llcsharp/operation/method.ts

Please refer to https://github.com/Azure/autorest.powershell/issues/1344 for details.

Add support for operation-location

---

tools/docker/Dockerfile

1. Upgrade ubuntu from 18.04 to 22.04
2. Upgrade node to 18.20.4
3. Upgrade dotnet SDK from core 2.1 to dotnet 8

Upgrade docker for codegen

---

rush.json

Update rush.json for test

---

rush.json

Reverts Azure/autorest.powershell#1354

Revert "Update rush.json for test"

---

powershell/utils/model-state.ts

Reverts Azure/autorest.powershell#1364

Revert "tsp - add support for output-folder"

---

common/config/rush/pnpm-lock.yaml
packages/typespec-powershell/configuration.yaml
packages/typespec-powershell/package.json
packages/typespec-powershell/src/emitter.ts

Move some common configurations from tspconfig.yaml to the emitter.

tsp - move common config to the emitter

---

powershell/cmdlets/class.ts

[Fixed issue](https://github.com/Azure/autorest.powershell/issues/1374)

Fix 1374, need to check parent model for itemName for pageable api

---

powershell/plugins/create-commands-v2.ts

Fix createOrUpdateRegex in command description

---

powershell/cmdlets/class.ts
powershell/internal/project.ts
powershell/llcsharp/model/namespace.ts
powershell/llcsharp/project.ts
powershell/llcsharp/schema/schema-resolver.ts
powershell/models/model-extensions.ts
powershell/plugins/cs-namer-v2.ts
powershell/plugins/sdk-cs-namer.ts
powershell/plugins/sdk-tweak-model.ts

When fixed-array is set to true, we will generate a fixed array in model. Otherwise we will generate list.

Add the config fixed-array, which is false by default

---

powershell/sdk/utility.ts
tests-upgrade/tests-sdk1-support/model-validate/csharp/Models/Operation.cs
tests-upgrade/tests-sdk1-support/model-validate/swagger.json

Fixed https://github.com/Azure/autorest.powershell/issues/1391

SDK - Add support for decimal

---

powershell/plugins/sdk-cs-namer.ts
powershell/resources/templates/methodBodyRestCall.ejs
tests-upgrade/tests-emitter/Sphere.Management/target/generate-portal-ux.ps1

Fixed the issue https://github.com/Azure/autorest.powershell/issues/1401.

Fixed a group parameter related issue

---

packages/typespec-powershell/src/emitter.ts

tsp - add configuration emit-modeler-output to control whether to generate modeler

---

.azure-pipelines/pr-validation.yml

increase pr-validation pipeline parallel job to decrease build time

increase pr-validation pipeline parallel job to decrease build time

---

powershell/resources/assets/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/AppComplianceAutomation.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Astronomer.Astro.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/AzureAI.Assets/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/AzureFleet.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/AzureLargeInstance.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/CodeSigning.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/ComputeSchedule.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/DeviceRegistry.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/DocumentDB.MongoCluster.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/EdgeZones.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/HealthDataAIServices.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Informatica.DataManagement.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/KubernetesRuntime.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/LambdaTest.HyperExecute.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Liftr.WeightsAndBiases.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Microsoft.DevOpsInfrastructure.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Neon.Postgres.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/NetworkAnalytics.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Pinecone.VectorDb.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Qumulo.Storage.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Sphere.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/StandbyPool.Management/target/create-model-cmdlets.ps1
tests-upgrade/tests-emitter/Workloads.SAPVirtualInstance.Management/target/create-model-cmdlets.ps1

Fixed issue https://github.com/Azure/autorest.powershell/issues/931

Add prefix support for model-cmdlet

---

powershell/generators/gitignore.ts

Consider move model cmdlet out from custom folder in the future

Remove model cmdlets from gitignore
